[2024-12-01T12:11:44.565+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: car_price_prediction.predict scheduled__2023-01-10T15:00:00+00:00 [queued]>
[2024-12-01T12:11:44.573+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: car_price_prediction.predict scheduled__2023-01-10T15:00:00+00:00 [queued]>
[2024-12-01T12:11:44.573+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T12:11:44.575+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-01T12:11:44.575+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-01T12:11:44.593+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): predict> on 2023-01-10 15:00:00+00:00
[2024-12-01T12:11:44.601+0000] {standard_task_runner.py:55} INFO - Started process 720 to run task
[2024-12-01T12:11:44.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'car_price_prediction', 'predict', 'scheduled__2023-01-10T15:00:00+00:00', '--job-id', '821', '--raw', '--subdir', 'DAGS_FOLDER/hw_dag.py', '--cfg-path', '/tmp/tmpysycmzn9']
[2024-12-01T12:11:44.606+0000] {standard_task_runner.py:83} INFO - Job 821: Subtask predict
[2024-12-01T12:11:44.672+0000] {task_command.py:388} INFO - Running <TaskInstance: car_price_prediction.predict scheduled__2023-01-10T15:00:00+00:00 [running]> on host 88c3fb750b90
[2024-12-01T12:11:44.740+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=car_price_prediction
AIRFLOW_CTX_TASK_ID=predict
AIRFLOW_CTX_EXECUTION_DATE=2023-01-10T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-10T15:00:00+00:00
[2024-12-01T12:11:44.744+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/modules/predict.py", line 15, in predict
    model = dill.load(file)
  File "/home/airflow/.local/lib/python3.7/site-packages/dill/_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/airflow/.local/lib/python3.7/site-packages/dill/_dill.py", line 472, in load
    obj = StockUnpickler.load(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/dill/_dill.py", line 462, in find_class
    return StockUnpickler.find_class(self, module, name)
AttributeError: Can't get attribute '_create_code' on <module 'dill._dill' from '/home/***/.local/lib/python3.7/site-packages/dill/_dill.py'>
[2024-12-01T12:11:44.757+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=car_price_prediction, task_id=predict, execution_date=20230110T150000, start_date=20241201T121144, end_date=20241201T121144
[2024-12-01T12:11:44.770+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 821 for task predict (Can't get attribute '_create_code' on <module 'dill._dill' from '/home/***/.local/lib/python3.7/site-packages/dill/_dill.py'>; 720)
[2024-12-01T12:11:44.816+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-01T12:11:44.835+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
